### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by geoidesic** [lorenzo/cakephp3-bookmarkr#3]
I followed the instructions but I get errors:
```
Notice (8): compact(): Undefined variable: etagMatches [CORE/src/Network/Response.php, line 1194]
Notice (8): compact() [function.compact]: Undefined variable: timeMatches [CORE/src/Network/Response.php, line 1194]
Notice (8): compact() [function.compact]: Undefined variable: etagMatches [CORE/src/Network/Response.php, line 1194]
Notice (8): compact() [function.compact]: Undefined variable: timeMatches [CORE/src/Network/Response.php, line 1194]

Warning: count() [function.count]: Parameter must be an array or an object that implements Countable in /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Database/QueryCompiler.php on line 118

Warning: count() [function.count]: Parameter must be an array or an object that implements Countable in /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Database/QueryCompiler.php on line 118
Warning (2): count() [function.count]: Parameter must be an array or an object that implements Countable [CORE/src/Database/QueryCompiler.php, line 118]

Warning: count() [function.count]: Parameter must be an array or an object that implements Countable in /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Database/QueryCompiler.php on line 118

Warning: count() [function.count]: Parameter must be an array or an object that implements Countable in /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Database/QueryCompiler.php on line 118
Warning (2): count() [function.count]: Parameter must be an array or an object that implements Countable [CORE/src/Database/QueryCompiler.php, line 118]
Warning (2): Declaration of Carbon\Carbon::setTime($hour, $minute, $second = 0) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL) [ROOT/vendor/nesbot/carbon/src/Carbon/Carbon.php, line 2203]
An Internal Error Has Occurred

Error: Please pass "username" instead of "login" for connecting to the database


Fatal error: Uncaught Error: Call to a member function getTrace() on string in /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Template/Element/exception_stack_trace.ctp:21 Stack trace: #0 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/View/View.php(815): include() #1 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/View/View.php(775): Cake\View\View->_evaluate('/Users/noeldaco...', Array) #2 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/View/View.php(1139): Cake\View\View->_render('/Users/noeldaco...', Array) #3 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/View/View.php(374): Cake\View\View->_renderElement('/Users/noeldaco...', Array, Array) #4 /Users/me/repo/bookmarker/src/Template/Error/error500.ctp(12): Cake\View\View->element('exception_stack...') #5 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/View/View.php(815): include('/Users/noeldaco...') #6 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/View/View. in /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Template/Element/exception_stack_trace.ctp on line 21
Warning (2): ini_set() [function.ini-set]: Headers already sent. You cannot change the session module's ini settings at this time [CORE/src/Network/Session.php, line 289]

Warning: ini_set() [function.ini-set]: Headers already sent. You cannot change the session module's ini settings at this time in /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Network/Session.php on line 289

Fatal error: [RuntimeException] Unable to configure the session, setting session.use_trans_sid failed. #0 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Network/Session.php(212): Cake\Network\Session->options(Array) #1 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Network/Session.php(119): Cake\Network\Session->__construct(Array) #2 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Network/Request.php(185): Cake\Network\Session::create(Array) #3 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(105): Cake\Network\Request::createFromGlobals() #4 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(90): Cake\Error\ExceptionRenderer->_getController() #5 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(142): Cake\Error\ExceptionRenderer->__construct(Object(Cake\Error\FatalErrorException)) #6 /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Error/BaseErrorHandl in /Users/me/repo/bookmarker/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 155
```

**Comment by geoidesic** [comment]
PHP 7.3.7 and I did change "login" to "username" but that didn't seem to help.

**Comment by geoidesic** [comment]
Fatal error: Cannot use Crud\Core\Object as Object because 'Object' is a special class name in /Users/me/cakephp3-bookmarkr/vendor/friendsofcake/crud/src/Listener/BaseListener.php on line 4

**Comment by tlshifat** [comment]
its not working at all. Please remove this github project
